---
title: "Insta Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r, }
data("instacart")
instacart = 
            instacart %>%
              janitor::clean_names() %>%
  mutate(reordered = as_factor(reordered)
  ) %>%
                filter(
                        !is.na(department_id), 
                          order_number %in% 20:100, add_to_cart_order %in% 20:100, 
                        days_since_prior_order %in% 1:3 )
        
```

Column {data-width=650}
-----------------------------------------------------------------------

### A plot showing the quantities of products ordered at different hours of the day
```{r}
instacart %>%
  mutate(text_label = str_c("Department: ", department, "\nProduct: ", product_name)) %>% 
  plot_ly(
    x = ~order_hour_of_day, y = ~order_number, type = "scatter", mode = "markers",
    color = ~department, text = ~text_label, alpha = 0.5)

```

Column {data-width=350}
-----------------------------------------------------------------------

### A box plot showing how frequently different products from different departments are ordered on instacart

```{r}
instacart %>%
   mutate(text_label1 = str_c("Department: ", department, "\nProduct: ", product_name)) %>%
  plot_ly(y = ~days_since_prior_order, color = ~department, type = "box", colors = "viridis")
```

### A frequency plot of different departments

```{r}
instacart %>%
  count(department) %>%
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis")

```